### ISSUE TITLE
About setMinInhabitedTime

### ISSUE THREAD

**Issue by Soapy7261** [aternosorg/thanos#12]
Is this in seconds or minutes or something else? Since i wanna increase this for my end since players do a lot of elytra gliding and it makes a lot of unneeded chunks, but i don't wanna make it so end ships could be reset and that'd be bad
I use the default thanos.php file

**Comment by JulianVennen** [comment]
> The cumulative number of ticks players have been in this chunk.

https://minecraft.fandom.com/wiki/Chunk_format#NBT_structure

So it's

**Comment by Soapy7261** [comment]
Ohhhh its ticks alright thanks
