### ISSUE TITLE
Error While Running The Software

### ISSUE THREAD

**Issue by SaumyaKhobragade** [aternosorg/thanos#13]
![image](https://user-images.githubusercontent.com/78600365/218096901-06bdc252-3f45-47ed-9c20-fb80d1c912f8.png)

I am having this error when I try to delete chunks from my world. Is it happening because of the size (14gb)?

**Comment by KurtThiemann** [comment]
Could you check that there are no corrupted chunks in your world using Minecraft Region Fixer (https://github.com/Fenixin/Minecraft-Region-Fixer)?
It would also be helpful if you could send me the world in question, although I understand that this might be impractical due to its size.

**Comment by SaumyaKhobragade** [comment]
I will try to check for corrupted chunks, and will let you know the status. Thanks!

**Comment by SaumyaKhobragade** [comment]
So I tried using the region fixer and here are the results:
![image](https://user-images.githubusercontent.com/78600365/218245598-02cb2464-1af9-47d5-9391-259b501de41e.png)

**Comment by SaumyaKhobragade** [comment]
Removing The Corrupted Chunks Worked For Me. Thanks!
