### ISSUE TITLE
How to use it in a minecraft server?

### ISSUE THREAD

**Issue by pokecosimo** [aternosorg/thanos#16]
How to use it in a minecraft server?

**Comment by KurtThiemann** [comment]
Thanos is a standalone cli tool, not a mod or plugin. How to use it is explained here: https://github.com/aternosorg/thanos#cli-tool

**Comment by pokecosimo** [comment]
> Thanos is a standalone cli tool, not a mod or plugin. How to use it is explained here: https://github.com/aternosorg/thanos#cli-tool

ok, but i whanted to put it in my vps to make it like in aternos

**Comment by KurtThiemann** [comment]
After installing php and composer on your VPS, you can just clone the repository, run `composer install` inside the thanos directory, and then use the `thanos.php` file like described in the README. 

Please note that thanos should only be run while the server is stopped.
