### ISSUE TITLE
Failed to inflate input data.

### ISSUE THREAD

**Issue by Learting** [aternosorg/thanos#17]
Hello, I am trying to use this tool but this error always occurs. I don't know how to solve it on my own.

PHP Warning:  inflate_add(): data error in /home/learting/vendor/aternos/thanos/src/Reader/ZlibReader.php on line 108
Failed to inflate input data.
PHP Fatal error:  Uncaught Exception: Failed to inflate input data. in /home/learting/vendor/aternos/thanos/src/Reader/ZlibReader.php:113
Stack trace:
#0 /home/learting/vendor/aternos/thanos/src/Chunk/AnvilChunk.php(200): Aternos\Thanos\Reader\ZlibReader->read()
#1 /home/learting/vendor/aternos/thanos/src/Chunk/AnvilChunk.php(168): Aternos\Thanos\Chunk\AnvilChunk->readAfter()
#2 /home/learting/vendor/aternos/thanos/src/Task/RegionTask.php(39): Aternos\Thanos\Chunk\AnvilChunk->getInhabitedTime()
#3 [internal function]: Aternos\Thanos\Task\RegionTask->run()
#4 /home/learting/vendor/aternos/taskmaster/src/Runtime/Runtime.php(72): Fiber->start()
#5 /home/learting/vendor/aternos/taskmaster/src/Communication/RequestHandler.php(65): Aternos\Taskmaster\Runtime\Runtime->runTask()
#6 /home/learting/vendor/aternos/taskmaster/src/Communication/RequestHandlingTrait.php(69): Aternos\Taskmaster\Communication\RequestHandler->handle()
#7 /home/learting/vendor/aternos/taskmaster/src/Communication/Socket/SocketCommunicatorTrait.php(79): Aternos\Taskmaster\Runtime\Runtime->handleRequest()
#8 /home/learting/vendor/aternos/taskmaster/src/Runtime/SocketRuntime.php(88): Aternos\Taskmaster\Runtime\SocketRuntime->update()
#9 /home/learting/vendor/aternos/taskmaster/src/Environment/Fork/ForkWorkerInstance.php(56): Aternos\Taskmaster\Runtime\SocketRuntime->start()
#10 /home/learting/vendor/aternos/taskmaster/src/Worker/Worker.php(118): Aternos\Taskmaster\Environment\Fork\ForkWorkerInstance->start()
#11 /home/learting/vendor/aternos/taskmaster/src/Worker/Worker.php(93): Aternos\Taskmaster\Worker\Worker->startInstance()
#12 /home/learting/vendor/aternos/taskmaster/src/Worker/Worker.php(197): Aternos\Taskmaster\Worker\Worker->getInstance()
#13 /home/learting/vendor/aternos/taskmaster/src/Taskmaster.php(269): Aternos\Taskmaster\Worker\Worker->assignTask()
#14 /home/learting/vendor/aternos/taskmaster/src/Taskmaster.php(234): Aternos\Taskmaster\Taskmaster->assignNextTaskToWorkerIfPossible()
#15 /home/learting/vendor/aternos/taskmaster/src/Taskmaster.php(168): Aternos\Taskmaster\Taskmaster->update()
#16 /home/learting/vendor/aternos/thanos/src/Thanos.php(78): Aternos\Taskmaster\Taskmaster->waitAndHandleTasks()
#17 /home/learting/vendor/aternos/thanos/thanos.php(42): Aternos\Thanos\Thanos->snap()
#18 {main}
  thrown in /home/learting/vendor/aternos/thanos/src/Reader/ZlibReader.php on line 113

**Comment by KurtThiemann** [comment]
That error indicates that your world contains corrupted data. Could you try using Minecraft Region Fixer first to resolve any potential problems in your world files first?
https://github.com/Fenixin/Minecraft-Region-Fixer
