### ISSUE TITLE
Getting Issues with the new version

### ISSUE THREAD

**Issue by SaumyaKhobragade** [aternosorg/thanos#19]
E:\Minecraft Files\thanos>php ./vendor/aternos/thanos/thanos.php ./world ./newworld
PHP Warning:  stream_socket_pair(): Failed to create sockets: [10042]: An unknown, invalid, or unsupported option or level was specified in a getsockopt or setsockopt call in E:\Minecraft Files\thanos\vendor\aternos\taskmaster\src\Communication\Socket\SocketPair.php on line 25
PHP Warning:  Trying to access array offset on false in E:\Minecraft Files\thanos\vendor\aternos\taskmaster\src\Communication\Socket\SocketPair.php on line 26
PHP Fatal error:  Uncaught TypeError: stream_set_blocking(): Argument #1 ($stream) must be of type resource, null given in E:\Minecraft Files\thanos\vendor\aternos\taskmaster\src\Communication\Socket\Socket.php:38
Stack trace:
#0 E:\Minecraft Files\thanos\vendor\aternos\taskmaster\src\Communication\Socket\Socket.php(38): stream_set_blocking()
#1 E:\Minecraft Files\thanos\vendor\aternos\taskmaster\src\Communication\Socket\SocketPair.php(26): Aternos\Taskmaster\Communication\Socket\Socket->__construct()
#2 E:\Minecraft Files\thanos\vendor\aternos\taskmaster\src\Runtime\RuntimeProcess.php(34): Aternos\Taskmaster\Communication\Socket\SocketPair->__construct()
#3 E:\Minecraft Files\thanos\vendor\aternos\taskmaster\src\Environment\Process\ProcessWorkerInstance.php(39): Aternos\Taskmaster\Runtime\RuntimeProcess->__construct()
#4 E:\Minecraft Files\thanos\vendor\aternos\taskmaster\src\Worker\Worker.php(118): Aternos\Taskmaster\Environment\Process\ProcessWorkerInstance->start()
#5 E:\Minecraft Files\thanos\vendor\aternos\taskmaster\src\Worker\Worker.php(93): Aternos\Taskmaster\Worker\Worker->startInstance()
#6 E:\Minecraft Files\thanos\vendor\aternos\taskmaster\src\Worker\Worker.php(197): Aternos\Taskmaster\Worker\Worker->getInstance()
#7 E:\Minecraft Files\thanos\vendor\aternos\taskmaster\src\Taskmaster.php(269): Aternos\Taskmaster\Worker\Worker->assignTask()
#8 E:\Minecraft Files\thanos\vendor\aternos\taskmaster\src\Taskmaster.php(234): Aternos\Taskmaster\Taskmaster->assignNextTaskToWorkerIfPossible()
#9 E:\Minecraft Files\thanos\vendor\aternos\taskmaster\src\Taskmaster.php(168): Aternos\Taskmaster\Taskmaster->update()
#10 E:\Minecraft Files\thanos\vendor\aternos\thanos\src\Thanos.php(78): Aternos\Taskmaster\Taskmaster->waitAndHandleTasks()
#11 E:\Minecraft Files\thanos\vendor\aternos\thanos\thanos.php(42): Aternos\Thanos\Thanos->snap()
#12 {main}
  thrown in E:\Minecraft Files\thanos\vendor\aternos\taskmaster\src\Communication\Socket\Socket.php on line 38
  
  
  These are the error logs ^^

**Comment by KurtThiemann** [comment]
Which was the last version of Thanos that you were able to run on your system? While we'd have to look into that further, it seems like our "multithreading" library doesn't work correctly on Windows.
Could you try if Thanos works correctly with multithreading disabled (set the environment variable `TASKMASTER_WORKER=sync`)?

**Comment by SaumyaKhobragade** [comment]
I never used thanos before. This is my 1st installation. 
E:\Minecraft_Files\thanos>php ./vendor/aternos/thanos/thanos.php ./world ./newworld
PHP Warning:  stream_socket_pair(): Failed to create sockets: [10042]: An unknown, invalid, or unsupported option or level was specified in a getsockopt or setsockopt call in E:\Minecraft_Files\thanos\vendor\aternos\taskmaster\src\Communication\Socket\SocketPair.php on line 25
PHP Warning:  Trying to access array offset on false in E:\Minecraft_Files\thanos\vendor\aternos\taskmaster\src\Communication\Socket\SocketPair.php on line 26
PHP Fatal error:  Uncaught TypeError: stream_set_blocking(): Argument #1 ($stream) must be of type resource, null given in E:\Minecraft_Files\thanos\vendor\aternos\taskmaster\src\Communication\Socket\Socket.php:38
Stack trace:
#0 E:\Minecraft_Files\thanos\vendor\aternos\taskmaster\src\Communication\Socket\Socket.php(38): stream_set_blocking()
#1 E:\Minecraft_Files\thanos\vendor\aternos\taskmaster\src\Communication\Socket\SocketPair.php(26): Aternos\Taskmaster\Communication\Socket\Socket->__construct()
#2 E:\Minecraft_Files\thanos\vendor\aternos\taskmaster\src\Runtime\RuntimeProcess.php(34): Aternos\Taskmaster\Communication\Socket\SocketPair->__construct()
#3 E:\Minecraft_Files\thanos\vendor\aternos\taskmaster\src\Environment\Process\ProcessWorkerInstance.php(39): Aternos\Taskmaster\Runtime\RuntimeProcess->__construct()
#4 E:\Minecraft_Files\thanos\vendor\aternos\taskmaster\src\Worker\Worker.php(118): Aternos\Taskmaster\Environment\Process\ProcessWorkerInstance->start()
#5 E:\Minecraft_Files\thanos\vendor\aternos\taskmaster\src\Worker\Worker.php(93): Aternos\Taskmaster\Worker\Worker->startInstance()
#6 E:\Minecraft_Files\thanos\vendor\aternos\taskmaster\src\Worker\Worker.php(197): Aternos\Taskmaster\Worker\Worker->getInstance()
#7 E:\Minecraft_Files\thanos\vendor\aternos\taskmaster\src\Taskmaster.php(269): Aternos\Taskmaster\Worker\Worker->assignTask()
#8 E:\Minecraft_Files\thanos\vendor\aternos\taskmaster\src\Taskmaster.php(234): Aternos\Taskmaster\Taskmaster->assignNextTaskToWorkerIfPossible()
#9 E:\Minecraft_Files\thanos\vendor\aternos\taskmaster\src\Taskmaster.php(168): Aternos\Taskmaster\Taskmaster->update()
#10 E:\Minecraft_Files\thanos\vendor\aternos\thanos\src\Thanos.php(78): Aternos\Taskmaster\Taskmaster->waitAndHandleTasks()
#11 E:\Minecraft_Files\thanos\vendor\aternos\thanos\thanos.php(42): Aternos\Thanos\Thanos->snap()
#12 {main}
  thrown in E:\Minecraft_Files\thanos\vendor\aternos\taskmaster\src\Communication\Socket\Socket.php on line 38
  
  I get this error with the variable set ^^
![image](https://github.com/aternosorg/thanos/assets/78600365/ff16288f-f035-45d6-bf05-51c3a5032a20)

**Comment by SaumyaKhobragade** [comment]
![image](https://github.com/aternosorg/thanos/assets/78600365/222e301f-2fda-4075-85bf-3ae35b2abacf)
I meant to send this mb

**Comment by KurtThiemann** [comment]
I think you need to use `set` to set an environment variable on Windows: https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/set_1

```
set TASKMASTER_WORKER=sync
php ./vendor/aternos/thanos/thanos.php ./world ./newworld
```

**Comment by SaumyaKhobragade** [comment]
I did use it and that's what the last screenshot sent by me is of. I mean its a proof that I set using the set command.

**Comment by KurtThiemann** [comment]
I’ll set up a Windows VM and see if I can find a workaround on monday. For now, using version 0.6.0 should work (except if you need LZ4 support), since that was before multithreading was added. Otherwise, you can try running the latest version in wsl or a Linux vm.

**Comment by SaumyaKhobragade** [comment]
Thanks a lot for the help. I will try downgrading the version and seeing if it reproduces. I will update it here!

**Comment by SaumyaKhobragade** [comment]
Yeah, version 0.6.0 had no issues with working. 
![image](https://github.com/aternosorg/thanos/assets/78600365/8b4ab9b1-26d0-4cf8-ad7e-a4b831ed1b08)

**Comment by KurtThiemann** [comment]
Version 0.8.3 should work on Windows, although slower than on Linux, since everything is done synchronously.
