### ISSUE TITLE
Error while trying to use .thanos

### ISSUE THREAD

**Issue by XShoutGamer** [aternosorg/thanos#9]
When I use Thanos on my world it works but then after a small while I get an error. I would like to know how to fix this.

error:
![image](https://user-images.githubusercontent.com/90159410/147689517-99a1100d-89c3-41d1-8da7-d17dff786651.png)

**Comment by KurtThiemann** [comment]
Could you attach (a link to) the world you are trying to use thanos on?
From the error message, it sounds like there is an invalid/corrupted chunk in your world.

**Comment by XShoutGamer** [comment]
> Could you attach (a link to) the world you are trying to use thanos on? From the error message, it sounds like there is an invalid/corrupted chunk in your world.

I cant attach the file because the file is too large (30gb in size)

**Comment by KurtThiemann** [comment]
Try using Minecraft Region Fixer (https://github.com/Fenixin/Minecraft-Region-Fixer ) to find and remove broken chunks before using thanos.
